# can use variables like {build} and {branch}
version: 1.0.{build}

image: Visual Studio 2017

environment:
  BUILD_DIR: "%APPVEYOR_BUILD_FOLDER%\\build"

platform:
  - Win32

configuration:
  - Debug

before_build:
  - cd %BUILD_DIR%
  - cmake .. -DBUILD_TESTING=ON -Dlibuv_buildtests=OFF -G"Visual Studio 15 2017"

build:
  parallel: true
  project: build/uvw.sln
  verbosity: minimal
